services:
    victoire_core.widget_slider.content_resolver:
        parent: victoire_core.widget_listing_content_resolver
        tags:
            - {name: victoire_widget.widget_content_resolver, alias: Slider}
    #alias to the entity
    victoire.widget.slider:
        class: Victoire\Widget\SliderBundle\Entity\WidgetSlider
        tags:
            - { name: victoire_core.widget, widget: listing }


    #alias to the form
    victoire.widget.form.slider:
        class: Victoire\Widget\SliderBundle\Form\WidgetSliderType
        tags:
            - { name: form.type }

    #alias to the form
    victoire.widget.form.slideritem:
        class: Victoire\Widget\SliderBundle\Form\WidgetSliderItemType
        tags:
            - { name: form.type }
